import { ReactComponent as Info1 } from "@Asset/Landing/info1.svg";
import { ReactComponent as Info2 } from "@Asset/Landing/info2.svg";
import { ReactComponent as Info3 } from "@Asset/Landing/info3.svg";
import { ReactComponent as Info4 } from "@Asset/Landing/info4.svg";
import { ReactComponent as Info5 } from "@Asset/Landing/info5.svg";
import { ReactComponent as Info6 } from "@Asset/Landing/info6.svg";
import { ReactComponent as MetImage1 } from "@Asset/Landing/met_image1.svg";
import { ReactComponent as MetImage2 } from "@Asset/Landing/met_image2.svg";
import { ReactComponent as Sky1 } from "@Asset/Landing/sky_01.svg";
import { ReactComponent as Sky2 } from "@Asset/Landing/sky_02.svg";
import { ReactComponent as Star1 } from "@Asset/Landing/star1.svg";
import { ReactComponent as Star2 } from "@Asset/Landing/star2.svg";
import { ReactComponent as JoyStick } from "@Asset/Landing/joystick.svg";
import { ReactComponent as Heart1 } from "@Asset/Landing/heart1.svg";
import { ReactComponent as Heart2 } from "@Asset/Landing/heart2.svg";
import { ReactComponent as SeonGu } from "@Asset/Landing/Seongu.svg";
import { ReactComponent as Moon } from "@Asset/Landing/moon1.svg";
import { ReactComponent as LandingBottomWave1 } from "@Asset/Landing/landing_bottom_wave1.svg";
import { ReactComponent as LandingBottomWave2 } from "@Asset/Landing/landing_bottom_wave2.svg";
import { ReactComponent as LandingBottomWave3 } from "@Asset/Landing/landing_bottom_wave3.svg";
import { ReactComponent as LandingBottomWave4 } from "@Asset/Landing/landing_bottom_wave4.svg";
import { ReactComponent as Sign } from "@Asset/METAJOU2022.svg";
import { ReactComponent as FaceBook } from "@Asset/facebook.svg";
import { ReactComponent as Insta } from "@Asset/insta.svg";

export { Sign, FaceBook, Insta, LandingBottomWave1, LandingBottomWave2, LandingBottomWave3, LandingBottomWave4, Info1, Info2, Info3, Info4, Info5, Info6, MetImage1, MetImage2, Sky1, Sky2, Star1, Star2, JoyStick, Heart1, Heart2, SeonGu, Moon };
